# gen-attribution.ps1
# Walk curated STK assets, collect their .license files, and emit
# ATTRIBUTION.md. Run this any time you add or remove imported assets.
#
# Usage:
#   pwsh ./gen-attribution.ps1
#
# The output is ATTRIBUTION.md next to this script — ship it with every
# build so CC-BY-SA attribution requirements are met.

param(
    [string]$Source = "$PSScriptRoot\curated",
    [string]$Out = "$PSScriptRoot\ATTRIBUTION.md"
)

$ErrorActionPreference = "Stop"

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# Asset attribution")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("Kartchain reuses art and audio from the [SuperTuxKart](https://supertuxkart.net/) project.")
[void]$sb.AppendLine("All assets below are © their original authors and licensed under")
[void]$sb.AppendLine("[Creative Commons Attribution-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/)")
[void]$sb.AppendLine("unless an individual `.license` file says otherwise.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("Generated by ``assets-import/gen-attribution.ps1`` on $(Get-Date -Format 'yyyy-MM-dd').")
[void]$sb.AppendLine("")

if (-not (Test-Path $Source)) {
    Write-Warning "No curated folder at $Source. Copy STK assets in and rerun."
    Set-Content -Path $Out -Value $sb.ToString()
    exit 0
}

Get-ChildItem -Path $Source -Directory | Sort-Object Name | ForEach-Object {
    $kind = $_.Name  # karts | tracks | music
    [void]$sb.AppendLine("## $kind")
    [void]$sb.AppendLine("")
    Get-ChildItem -Path $_.FullName -Directory | Sort-Object Name | ForEach-Object {
        $assetDir = $_
        $license = Get-ChildItem -Path $assetDir.FullName -Filter "license*.txt" -ErrorAction SilentlyContinue | Select-Object -First 1
        if (-not $license) {
            $license = Get-ChildItem -Path $assetDir.FullName -Filter "*.license" -ErrorAction SilentlyContinue | Select-Object -First 1
        }
        if ($license) {
            $content = (Get-Content $license.FullName -Raw).Trim()
            [void]$sb.AppendLine("### $($assetDir.Name)")
            [void]$sb.AppendLine("")
            [void]$sb.AppendLine('```')
            [void]$sb.AppendLine($content)
            [void]$sb.AppendLine('```')
            [void]$sb.AppendLine("")
        } else {
            [void]$sb.AppendLine("### $($assetDir.Name)")
            [void]$sb.AppendLine("(no license file found — assume CC-BY-SA 4.0 per the STK repo default)")
            [void]$sb.AppendLine("")
        }
    }
}

Set-Content -Path $Out -Value $sb.ToString() -Encoding UTF8
Write-Host "Wrote $Out"
